"""Optional PyTorch policy-value network and bounded training tools."""

from nubia_training.neural.agents import MCTSAgent, NeuralPolicyAgent
from nubia_training.neural.checkpoints import (
    CHECKPOINT_VERSION,
    LoadedCheckpoint,
    load_checkpoint,
    save_checkpoint,
)
from nubia_training.neural.data import (
    ExampleProvenance,
    NeuralBatch,
    NeuralDatasetItem,
    ShardDataset,
    collate_examples,
)
from nubia_training.neural.device import select_device
from nubia_training.neural.evaluator import (
    PRIOR_SUM_TOLERANCE,
    CheckpointPositionEvaluator,
    NeuralPositionEvaluator,
    PositionEvaluation,
    PositionEvaluator,
    PyTorchPositionEvaluator,
)
from nubia_training.neural.iteration import (
    TRAINING_ITERATION_VERSION,
    IterationConfig,
    IterationResult,
    inspect_iteration,
    run_iteration,
)
from nubia_training.neural.losses import (
    LossResult,
    mask_policy_logits,
    policy_probabilities,
    sparse_policy_value_loss,
)
from nubia_training.neural.mcts import (
    MCTS_VERSION,
    MCTSConfig,
    MCTSSearchResult,
    RootChildStatistics,
    RootVisitPolicy,
    puct_score,
    run_mcts,
    search_state,
)
from nubia_training.neural.model import (
    MODEL_ARCHITECTURE_VERSION,
    ModelConfig,
    ModelOutput,
    PolicyValueNetwork,
    ResidualBlock,
    model_memory_report,
    trainable_parameter_count,
)
from nubia_training.neural.self_play import (
    SELF_PLAY_CORPUS_VERSION,
    SELF_PLAY_VERSION,
    SelfPlayConfig,
    SelfPlayCorpus,
    SelfPlayGame,
    SelfPlayPly,
    build_self_play_dataset,
    generate_self_play_corpus,
    inspect_self_play,
    load_self_play_corpus,
    play_self_play_game,
    read_self_play_game,
    self_play_examples,
    write_self_play_game,
)
from nubia_training.neural.training import (
    TRAINING_CONFIG_VERSION,
    EpochSummary,
    TrainingConfig,
    TrainingResult,
    TrainingSummary,
    seed_training,
    train_model,
)

__all__ = [
    "CHECKPOINT_VERSION",
    "MCTS_VERSION",
    "MODEL_ARCHITECTURE_VERSION",
    "PRIOR_SUM_TOLERANCE",
    "SELF_PLAY_CORPUS_VERSION",
    "SELF_PLAY_VERSION",
    "TRAINING_CONFIG_VERSION",
    "TRAINING_ITERATION_VERSION",
    "CheckpointPositionEvaluator",
    "EpochSummary",
    "ExampleProvenance",
    "IterationConfig",
    "IterationResult",
    "LoadedCheckpoint",
    "LossResult",
    "MCTSAgent",
    "MCTSConfig",
    "MCTSSearchResult",
    "ModelConfig",
    "ModelOutput",
    "NeuralBatch",
    "NeuralDatasetItem",
    "NeuralPolicyAgent",
    "NeuralPositionEvaluator",
    "PolicyValueNetwork",
    "PositionEvaluation",
    "PositionEvaluator",
    "PyTorchPositionEvaluator",
    "ResidualBlock",
    "RootChildStatistics",
    "RootVisitPolicy",
    "SelfPlayConfig",
    "SelfPlayCorpus",
    "SelfPlayGame",
    "SelfPlayPly",
    "ShardDataset",
    "TrainingConfig",
    "TrainingResult",
    "TrainingSummary",
    "build_self_play_dataset",
    "collate_examples",
    "generate_self_play_corpus",
    "inspect_iteration",
    "inspect_self_play",
    "load_checkpoint",
    "load_self_play_corpus",
    "mask_policy_logits",
    "model_memory_report",
    "play_self_play_game",
    "policy_probabilities",
    "puct_score",
    "read_self_play_game",
    "run_iteration",
    "run_mcts",
    "save_checkpoint",
    "search_state",
    "seed_training",
    "select_device",
    "self_play_examples",
    "sparse_policy_value_loss",
    "train_model",
    "trainable_parameter_count",
    "write_self_play_game",
]
