"""Public machine-learning representation foundation for NUBIA."""

from nubia_training.action_space import (
    ACTION_KIND_BLOCK_SIZE,
    ACTION_KIND_OFFSETS,
    ACTION_KIND_ORDER,
    ACTION_SPACE_SIZE,
    ACTION_SPACE_SPEC,
    ACTION_SPACE_VERSION,
    ActionSpaceSpec,
    action_to_index,
    index_to_action,
    legal_action_indices,
    legal_action_mask,
)
from nubia_training.encoding import (
    GLOBAL_FEATURE_NAMES,
    PIECE_TYPE_ORDER,
    SPATIAL_CHANNEL_NAMES,
    STATE_ENCODING_SPEC,
    STATE_ENCODING_VERSION,
    EncodedState,
    StateEncodingSpec,
    encode_state,
    encoded_states_equal,
    immediate_repetition_consequences,
)
from nubia_training.errors import (
    ActionIndexCollisionError,
    IllegalOrStaleActionError,
    InvalidActionIndexError,
    InvalidEncodingError,
    InvalidPolicyTargetError,
    RepresentationError,
    UnresolvedActionIndexError,
    UnsupportedActionKindError,
    UnsupportedPieceTypeError,
    VersionMismatchError,
)
from nubia_training.examples import (
    POLICY_SUM_TOLERANCE,
    TRAINING_EXAMPLE_VERSION,
    TrainingExample,
)

__all__ = [
    "ACTION_KIND_BLOCK_SIZE",
    "ACTION_KIND_OFFSETS",
    "ACTION_KIND_ORDER",
    "ACTION_SPACE_SIZE",
    "ACTION_SPACE_SPEC",
    "ACTION_SPACE_VERSION",
    "GLOBAL_FEATURE_NAMES",
    "PIECE_TYPE_ORDER",
    "POLICY_SUM_TOLERANCE",
    "SPATIAL_CHANNEL_NAMES",
    "STATE_ENCODING_SPEC",
    "STATE_ENCODING_VERSION",
    "TRAINING_EXAMPLE_VERSION",
    "ActionIndexCollisionError",
    "ActionSpaceSpec",
    "EncodedState",
    "IllegalOrStaleActionError",
    "InvalidActionIndexError",
    "InvalidEncodingError",
    "InvalidPolicyTargetError",
    "RepresentationError",
    "StateEncodingSpec",
    "TrainingExample",
    "UnresolvedActionIndexError",
    "UnsupportedActionKindError",
    "UnsupportedPieceTypeError",
    "VersionMismatchError",
    "action_to_index",
    "encode_state",
    "encoded_states_equal",
    "immediate_repetition_consequences",
    "index_to_action",
    "legal_action_indices",
    "legal_action_mask",
]
